### ISSUE TITLE
Tương tự bài 3. Nên đặt riêng 1 class BattleField. Thêm nữa là trong class Human có hàm kiểm tra xem đã chết chưa bool AlreadyDead()?

### ISSUE THREAD

**Issue by GuardianOfGods** [kocochj999/JavaLearningRepo#3]
https://github.com/kocochj999/JavaLearningRepo/blob/631908c21b36da9356ba9c028fd90ef48cbae14f/Week5/Bai4/src/RunMain/RunMain.java#L1-L42

**Comment by kocochj999** [comment]
oke để mai code lại đoạn này + đoạn chia class

**Comment by GuardianOfGods** [comment]
Thêm nữa bên trong hàm BattleField có cái hàm EndGame => if (A.AlreadyDead() || B.AlreadyDead()) ...
